name:                secure-gate
version:             0.1.0.0
github:              "githubuser/secure-gate"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/secure-gate#readme>

dependencies:
- base >= 4.7 && < 5
- binary >= 0.8.6
- cryptonite >= 0.25
- bytestring >= 0.10
- containers >= 0.6
- mtl >= 2.2
- vector >= 0.12
- ghc-prim >= 0.5.3
- zeromq4-haskell >= 0.8.0
- hashtables >= 1.2
- split >= 0.2
- template-haskell >= 2.14
- data-fix == 0.2.0

library:
  source-dirs: src

executables:
  secure-gate-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - secure-gate

tests:
  secure-gate-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - secure-gate
